# Set proper ruby version.
# Seems like the houndci doesn't have access to the .ruby-version file
# or the rubocop version is too old. The problem was actually solved by the
# rubocop developers with that PR:
# https://github.com/bbatsov/rubocop/issues/2956
AllCops:
  TargetRubyVersion: 2.6

Lint/Debugger:
  Enabled: false

# Indent when as deep as case.
Layout/CaseIndentation:
  Enabled: false

# Place the . on the next line, together with the method name.
Layout/DotPosition:
  EnforcedStyle: leading

# Extra empty line detected at class body beginning.
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Extra empty line detected at module body beginning.
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Missing space after #.
Layout/LeadingCommentSpace:
  Enabled: false

# Align group with DashboardStatSlave. on line 42.
Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

# %d trailing blank lines detected.
Layout/TrailingBlankLines:
  Enabled: false

# Block has too many lines. [27/25]
Metrics/BlockLength:
  Enabled: false

# Class has too many lines. [27/25]
Metrics/ClassLength:
  Enabled: false

# максимум 120 сиволов в 1 строке
Metrics/LineLength:
  Max: 120

# Module has too many lines. [27/25]
Metrics/ModuleLength:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Extra empty line detected at block body beginning.
Style/BlockDelimiters:
  Enabled: false

# Missing top-level class documentation comment.
Style/Documentation:
  Enabled: false

# do not freeze strings by default
Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/data/*.rb'

# Do not introduce global variables.
Style/GlobalVars:
  Enabled: false

# using [] with %w
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "[]"
    "%r": "{}"
    "%w": "[]"
    "%W": "[]"
    "%x": "[]"

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - 'spec/**/*.rb'
    - 'db/data/*.rb'

